### ISSUE TITLE
When adding a second observation two icon appear

### ISSUE THREAD

**Issue by shodge17** [citrit/iMapInvasiveSpeciesApp#15]
Start app
review preference
pick a species 
move the icon a bit
save
Now start a new record
pick a different species
go to the map.
drag the icon a bit.
a second icon appears
if you double click on the map the newly appeared icon seem to move to a new location
This action can also be seen if you have enter two obs and not uploaded them yet and then call one up to edit it.  At least on two occasions when I zoomed in (double click or using the minus sign) a second icon appeared and then appear to move.

On a fresh restart of the app both points appear to be in the correct position.

**Comment by citrit** [comment]
The second icon is a artifact from the previous observation, i am working on removing it now.

**Comment by citrit** [comment]
Fixed in version 1.0.6.
