### ISSUE TITLE
Imagery

### ISSUE THREAD

**Issue by shodge17** [citrit/iMapInvasiveSpeciesApp#17]
Has there been any thought about including an option to show imagery rather than the roads base map?  If you are in the middle of the woods in an off-line situation the imagery would be the best option.

**Comment by btkinal** [comment]
I agree with Stepehen,  If it is easy to change the "Where" map to be imagery or better yet hybrid of imagery and streets that would be most useful to our users

**Comment by citrit** [comment]
I am working on the map tonight so i will add an option to specify street
or terrain in the preferences. The same rules about being offline and
caching will apply.

Thanks.

Tom C.
