### ISSUE TITLE
Dropdown list updates

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#18]
Both the project list and species list get updated regularly how will these updates get passed to the app?

**Comment by citrit** [comment]
The Species and Project lists are actually in a DB file in the app. We talked about updating this and the easiest way it to start generating this DB file at FSU and regenerating the state specific apps and use the update capabilities of the phones AppStores. We need to have a call on this soon so Stephen and I can work out the details.

**Comment by citrit** [comment]
The app now communicates with FSU servers to get state projects and species. Updates can be manually made by simply selecting a different state then your original one.
