### ISSUE TITLE
Button Icons

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#20]
Button icons are attached. If possible lay them out on the home page 2 x 2:

Top Left = New Observation
Top Right = Edit Observation
Bottom Left = Upload
Bottom Right = Preferences

![edit](https://cloud.githubusercontent.com/assets/8700076/6693614/a32060c4-ccaa-11e4-8d23-674181f7bba6.png)
![observation](https://cloud.githubusercontent.com/assets/8700076/6693625/b6732bc0-ccaa-11e4-9333-e955dd925003.png)
![photo](https://cloud.githubusercontent.com/assets/8700076/6693627/b87e8928-ccaa-11e4-8aca-4e5a431a84a4.png)
![preferences](https://cloud.githubusercontent.com/assets/8700076/6693630/c0588626-ccaa-11e4-89e4-8c7b1fec2dec.png)
![upload2](https://cloud.githubusercontent.com/assets/8700076/6693814/19b75b60-ccac-11e4-98d3-a521865f637c.png)

**Comment by btkinal** [comment]
Not a priority right now but is it possible to have the icons laid out 2 x 2?

New Obs     Edit Obs
Upload         Preferences

**Comment by citrit** [comment]
Uploaded a new version with these changes.
