### ISSUE TITLE
Date picker is gone

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#22]
With the latest update the date picker doesn't pop up, the date is populated in a text box.

**Comment by citrit** [comment]
Yes, the date picker does not support time so i had to change it to a simple text box for now. We can change it later if I can find a better control.

**Comment by btkinal** [comment]
I am assuming we need the time sent to FREAC for upload purposes and that is why we had to get rid up the time picker.  If that's the case we have two date fields in the database one for the observation date and one for the data entry date. Would it be possible to auto generate the data entry date as a date time and allow the user to use the date picker to choose the observation date.  I can envision the text box for the date causing issues with our less tech savvy users.  The other thought would be just to hide the date option/tab and not just record the date/time of data entry.

**Comment by shodge17** [comment]
Say a person uses the app to capture an observation.  They then wait 1 month before they upload it.  If you are OK with FREAC just adding the date and time they uploaded it then we can handle that if you want.  There is a subtle difference between the meaning of data entry date if you enter a point online vs entering it with the phone app.  The phone app allows you to "do the data entry" and wait any amount of time before you hit the "submit" button.  On line you "do the data entry" and only have a few hours to hit the submit button before things timeout.

**Comment by btkinal** [comment]
It looks like Tom has fixed this without having to deal with the the scenario I brought up in my previous comment.  I'm not sure dealing important with the nuances of the data entry date, I see it to be more important for bulk uploads. I am fine with the data entry date being either the date the record was entered on the device or when it was added online, I would say whichever is easiest. But I think this may be a non-issue now.

**Comment by citrit** [comment]
The fix i put into place is the data entry field is a date with the picker. there is no change for time here  unless i add new functionality. Let me know how to handle this.

The other field is filed in at upload time and has a time component.

Does this work?

**Comment by mrchocoborider** [comment]
Just tested this, seems like the observation date is sans time component while the data entry date has the time component. Stephen and I think this works well since the actual date of observation may need to be edited after the fact (and it doesn't seem like time is very important here), while the data entry date should in fact be the date/time that the observation was made, where the time mostly acts as a helpful reference point for sorting through multiple obs entered on one day.

**Comment by citrit** [comment]
Can we close this one then?

**Comment by btkinal** [comment]
We are done here!!!
