### ISSUE TITLE
Update GPS Location

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#23]
Is it possible to add a button which will refresh the users GPS location on the map?  There will be times where the user may have moved from the location where they opened the map to get closer to the observation.

**Comment by btkinal** [comment]
The approach you took on this is fine, just curious what happens if point is dragged to a different location while GPS is active will it continue to update? I will go outside and test it in a few minutes.

**Comment by btkinal** [comment]
One other questions was just posed to me. Say you get to the map and realize that you had your GPS turned off.  If you turn it on while on the map will it recognize it. I will also try testing it when I can get outside.

**Comment by btkinal** [comment]
I answered both of my previous questions, one had a the answer I had hoped for and the other unfortunately didn't.

1. If you turn your GPS on after getting to the map page the app will recognize the GPS signal and update your position. This is good.

2. If you reposition the teardrop locator manually and then wait it will snap back to the GPS location.
This has the potential for problems if the user doesn't move fast enough to save the record. 

Is it possible to have the user initiate the GPS update via a button rather than have it be automatic every 10 sec.?  This would solve the issue.

**Comment by citrit** [comment]
I would strongly leaving it the way it is for now. The user can simply save the entry once input, it is only a few clicks. They can then edit the entry and move the icon to a new position without any updates.

The reason i say this is that the GPS will get more accurate over time, there is a strong possibility that the first reading may be way off and will get accurate as the user is filling in the data. So for new entries the GPS is active, for edit an observation the GPS update is off.

**Comment by shodge17** [comment]
what happens if a user is entering a point and moves it to the desired location and then decide they need to go back and review some of the other tabs before saving the record.  Lets say ti takes them 1 minute to go back and pick the right species.  Will the point in the mean time revert to the GPS position without them knowing or when you leave the map tap, the point is "frozen" where they left it?

**Comment by citrit** [comment]
The flow would be as the user is entering a new observation (only the save and cancel buttons are active) the system will update the position. Once they save the observation the update to GPS position is stopped. If they then go back to edit the observation then the position is fixed and no updates take place (this is when the save, cancel, and delete buttons are active). So a work flow would be:

1. Start a new observation, fill in the fields, check position. Save.
2. To change values while at a different location then edit will work fine, no changes to position are made by the app.

This is the simplest and i believe the easiest for people to follow. If we add too many buttons and options it can get confusing. Trust me, i have built a lot of software and giving users one simple way to do something eliminates confusion and support calls later. (and no I am not giving away my phone number as tech support ;).

**Comment by btkinal** [comment]
Two thoughts on this: If the user wants to save their point at its current position (either where the GPS has put it or where they have dragged it) they would need to quickly save the record before the 10 sec update refreshes the location. I have no problem with saving the record and freezing the location at this point, however the work flow for immediately checking that record then involves going back to opening edit from the main page, then finding the last record, and finally paging through the record to find the area to check or edit. I can foresee our users not liking this work flow, just knowing our users a few clicks is four too many. I have two thought on this.

1. Remove the map all together and just display the coordinate and accuracy. This is the approach that iNaturalist takes (see attached). Then if the user so desires they can refine their point online. (sorry I know that you put a lot of effort into the map)

![screenshot_2015-03-26-13-03-09 1](https://cloud.githubusercontent.com/assets/8700076/6852034/d358b33a-d3b8-11e4-8b36-ab6f5c02c2d5.png)


2.  Have the save button only "Save" the record and not exit the record. Then add a "Save and Close" button on the map page that saves the record and returns the user to the home page.
