### ISSUE TITLE
iPhone version and getting the app into the Google Play and App Store

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#24]
I think we are now at a point where we should work to get the apps into the two main mobile market places. A while back I had sent you an the contact info for getting on the ESF's Apple and Google dev. accounts, were you able to do that or would it be better if I get on the accounts? What kind of work is involved in getting the app ported to Apple?

We also need to have a discussion with Stephen regarding updates to the two drop down list (species list and project list) onto the app and post as an update to Google Play and the App Store.

**Comment by citrit** [comment]
We need to have a call on this, there are many ways to do this and we need to decide on the best mechanism. I have a live update way and a app store  way we need to discuss. Both have plusses and minuses so a conversation would help.

**Comment by citrit** [comment]
Both issues have been resolved as of 1.0.10 version.
