### ISSUE TITLE
Need to inform users that they need to have an iMap account to use the app

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#25]
In the preferences page can we add some text that informs the user that they need to register for iMapInvasives before they can upload data from the application to iMap.

Text:
"The iMapInvasives Mobile app is for registered users of New York iMapInvasives, to get an account click here: http://www.nyimapinvasives.org/request-login."

**Comment by citrit** [comment]
This is a great point that brings out a bigger discussion, currently the app is only for NY state. We have 2 options:

1. Create an app for every state that you want to support.
2. Add code to the app and services at FSU to download a state.

Question being is it enough to simply ask for a state and the FSU servers will supply all the needed data to make the app specific to that state. If we go with 2 then we need to define some data schemas to transfer all the projects and species specific to that state.

**Comment by btkinal** [comment]
I like option 2...one app to serve them all. (sorry I've been watching to may Tolkien movies),

I think it is time we do a phone call to discuss next steps. Would Monday afternoon work for all. As always I will probably just be a wallflower during the discussion.

**Comment by shodge17** [comment]
monday afternoon is fine with me.

**Comment by citrit** [comment]
App now gets info from FSU servers, one app to serve all states.
