### ISSUE TITLE
Text for app discription on app stoer

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#30]
Here is the text for the Google Play download page.

Title: iMapInvasives Mobile 

Short Description:
iMapInvasives Mobile for reporting invasive species to iMapInvasives online.
iMapInvasives account is required to use app.

Description:
iMapInvasives Mobile helps you report invasive species locations to your online iMapInvasives account by using your mobile device camera and GPS. You need to have an active iMapInvasives account for a participating state or province for observations to sync. To request a free account, visit www.imapinvasives.org/login.html

iMapInvasives provides an on-line, GIS-based data management system to assist citizen scientists and natural resource managers working to protect natural resources from the threat of invasive species. Find out more about the iMapInvasives Network at www.imapinvasives.org/index.html

**Comment by citrit** [comment]
I added the changes to the website, should be there by tomorrow. We should
also think about help text that I can embed in the app to help users. This
can be html pages or plain text.

Thanks

Tom C.

**Comment by citrit** [comment]
Text is in both Android and Apple app stores.
