### ISSUE TITLE
Imagery in Florida

### ISSUE THREAD

**Issue by shodge17** [citrit/iMapInvasiveSpeciesApp#31]
I have checked the Satellite option for the map type, but I only get the open street map view.

**Comment by citrit** [comment]
Sorry, i fixed the issue but then uploaded the App with the same version
number so it won't update. I will update the number and upload the new
version tonight.

**Comment by shodge17** [comment]
Perhaps I am a bit new to how all this works, but when I go to my apps and look at your app, it gives me 2 choices, 1) force stop and 2) uninstall.  There is no option for update.  So what I have been doing is uninstalling it and then reloading.  Is there a different procedure to just update or do you not have it set up like that?  Its fine either way, just thinking about instructions / phone calls that we may need.

**Comment by citrit** [comment]
All you need to do is update, that way it saves your preferences and any
observations you haven't uploaded yet.

Did it fix the satellite view issue?

Thanks

Tom C.

**Comment by shodge17** [comment]
Update is not an option on my Droid Turbo.  It looks like I have to uninstall and then reinstall.  thats no big deal, but most of the apps I have include the option to update.  Maybe it just my phone.... make you download again to use more data....

**Comment by shodge17** [comment]
The satellite fix you put in worked fine.... However  the icon is black, and the first place it comes up to when I am in my office is in a big shadow of the building and it is very difficult to see.  Can you make it say red or perhaps yellow (yellow is the color we have on the online version).

Also  for a future release, it would be nice to be able to set the road vs satellite option on the data entry page itself.

**Comment by citrit** [comment]
Changed the icon to be yellow, seems to work well over satellite imagery.
