### ISSUE TITLE
new back drop image for app.

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#32]
I had FREAC's graphics designer work on a new backdrop for the app. using the same graphics as the splash screen. She is also working on some new buttons to match.  Backdrop is attached
![mobile app 2](https://cloud.githubusercontent.com/assets/8700076/8332521/488fcb9a-1a5c-11e5-95fd-71fa3b20e623.gif)
Let me know if you need specific sizes. I will post button graphics as soon as I get them.

**Comment by citrit** [comment]
Included in the latest version.
