### ISSUE TITLE
Bug - Map on iPhone 6 covers multiple screens

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#38]
See Screen shots:

![img_0197](https://cloud.githubusercontent.com/assets/8700076/9174918/e0ea5cfc-3f50-11e5-99f7-f9f753f96f59.PNG)
![img_0192](https://cloud.githubusercontent.com/assets/8700076/9174920/e0edacb8-3f50-11e5-9c64-59d915ed0d90.PNG)
![img_0193](https://cloud.githubusercontent.com/assets/8700076/9174919/e0ed462e-3f50-11e5-967d-a45e9a66d592.PNG)
![img_0194](https://cloud.githubusercontent.com/assets/8700076/9174922/e0f1bb96-3f50-11e5-97aa-f46ee0e67083.PNG)
![img_0195](https://cloud.githubusercontent.com/assets/8700076/9174921/e0ef7ec6-3f50-11e5-8226-0365b071d385.PNG)

**Comment by btkinal** [comment]
Tom,  I think you are already aware of this and are working on it

**Comment by citrit** [comment]
Fixed in version 2
