### ISSUE TITLE
Error- Message on upload

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#39]
Meg got this when trying to upload multiple (14) records.  They all eventually uploaded but got the attached message several times between successful upload attempts. She would have to initiate the upload after seeing the message each time? Any thoughts? Should we just make the error message more descriptive, instructional?

![img_0198](https://cloud.githubusercontent.com/assets/8700076/9175034/701379b8-3f51-11e5-992d-92753780858d.PNG)

**Comment by btkinal** [comment]
I feel like this is under control now. If so we can close the ticket

**Comment by citrit** [comment]
I am pretty sure we did fix this one but lets leave it here in case it shows again.
