### ISSUE TITLE
Upload Bug....Multiple Uploads of the same record

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#41]
It seems like occasionally the app is not receiving the "ok" confirmation from iMap resulting in duplicate record for a single observation. I was wondering are we sending each obs in its own JSON string or are we sending all of them in one long string. If the latter would it maybe make sense to send them individually. We are still see issues with the upload either it is timing out or just hanging at times.

**Comment by citrit** [comment]
Fixed by FSU and in version 2.
