### ISSUE TITLE
"Uploading" popup disappears before upload is complete

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#42]
When uploading multiple observation records the popup box saying "uploading" disappears before the upload is complete returning the user to the upload list often resulting in the user initiating the upload again resulting in duplicate records. Is it possible to keep the pop up visible until the upload is complete and then once complete have a second pop up appear saying "Upload Complete"?

**Comment by citrit** [comment]
Fixed in version 2.
