### ISSUE TITLE
iPhone error message

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#48]
iPhone error message "No Access to Assets" and no camera.  iPhone 5, iOS v. 8.4.1
![image1](https://cloud.githubusercontent.com/assets/8700076/10074505/648b78a0-629e-11e5-8b91-2c21468ca950.png)

**Comment by citrit** [comment]
Is this on a specific iPhone? I never saw this error before, so how do I reproduce?

**Comment by citrit** [comment]
Does this still happen with the new version.

**Comment by jlmarino** [comment]
photo/media permissions have been re-worked in latest versions of app
