### ISSUE TITLE
Allow user to select photo from galary

### ISSUE THREAD

**Issue by btkinal** [citrit/iMapInvasiveSpeciesApp#56]
I know this presented upload issues in the past. If we can figure out how to make it work can we allow the user to choose photo from the galary.  While doing this can we also save a local copy of the photo take from the app.

**Comment by jlmarino** [comment]
I'd like to look into this as time allows for a future update. Additionally, I'd like to look into the capability to read the location metadata to determine where the photo was taken and pass that into the record's coordinates, similar to the way iNaturalist works.

**Comment by jlmarino** [comment]
In 2.0.48 (#63), you can now add a photo from the photo library and save original photos taken in iMap to the photo library.
