### ISSUE TITLE
Investigate photo corruption upon app update

### ISSUE THREAD

**Issue by jlmarino** [citrit/iMapInvasiveSpeciesApp#64]
Initial assessment is that upon app re-installation/update, the file path to the photos changes such that the original links to the photos are no longer valid.

**Comment by citrit** [comment]
I think this is expected and at one point we were suggesting that people upload all observations prior to upgrading or uninstalling the app.  I don't think it is worth it to try and fix in the code.

**Comment by jlmarino** [comment]
as of app version 3.0.1, this appears to be resolved.
